### ISSUE TITLE
More spectate bugs / loss of inventory.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#29]
RE: https://github.com/Efnilite/Walk-in-the-Park/issues/10

Compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/01146d59ea97780ff41f83805aeba1988d36de16

Found some more spectate bugs.

![link](https://i.imgur.com/Yge2sZ9.png)

1. Join WITP.
2. Spectate a player with the command ``/witp gamemode``.
3. Can spam ``/witp join`` despite already being part of parkour
-- **Bug 1** 
(Also works prior to spectating and spams join messages, should only be able to "join" parkour once and output already playing.)
4. After typing ``/witp join``, your game breaks. You get put in survival mode and back into your own course. However you can't move, your screen flashes red (as if you are dying), and you see your course's initial path generate infinitely in a repeating loop.
-- **Bug 2**
5. Leave spectate/parkour with the command ``/witp leave`` since you can't do anything.
6. You get teleported back to the person you were spectating and you are attached to them. However you are no longer a part of parkour. 
-- **Bug 3**
7. A If you leave with ``/spawn``, your inventory is wiped (get parkour inventory) & you are stuck in spectate gamemode.
7. B If you disconnect and reconnect, your inventory is wiped (get parkour inventory) & you are stuck in spectate gamemode.
7. C If you wait for the person you are stuck spectating to leave, you get put back in your course in survival (despite not being part of parkour). When you try to leave with ``/parkour leave``, you get put back into spectate gamemode, your spawn area despawns, & you are floating in the void. You then need to either do 7A or 7B, with inventory loss / getting stuck in gamemode spectate bug also occurring. 
-- **Bug 4**

**Comment by Efnilite** [comment]
Is every bug after using /witp join twice or more? I've fixed the double joining, which should fix a bunch of things.

**Comment by Efnilite** [comment]
These bugs were all due to the double joining (as far as I can tell since I'm experiencing none of them), so this has been fixed now

**Comment by mibby** [comment]
Double joining seem to be fixed. I do not believe spectating overwriting your leave location is fixed though.

i.e.

Join > Spectate > Leave Spectate > Leave WITP > get put in spectate location.

I'm also a bit weary about spectate gamemode bugs still existing such as relogging in spectate gamemode and losing inventory, but will need to do some more testing another time. Currently just have gamemode switching disabled.

**Comment by Efnilite** [comment]
> Double joining seem to be fixed. I do not believe spectating overwriting your leave location is fixed though.
> 
> i.e.
> 
> Join > Spectate > Leave Spectate > Leave WITP > get put in spectate location.
> 
> I'm also a bit weary about spectate gamemode bugs still existing such as relogging in spectate gamemode and losing inventory, but will need to do some more testing another time. Currently just have gamemode switching disabled.

I've tested the issue you stated here and for me it works on the latest dev build. Can you try again with the latest commit? (52f05c748f4ad2c7cf4b930b3bf3a1204485ce82)

**Comment by Efnilite** [comment]
Fixed in latest commit
